Piwik tracking
openfisca/tracker pull request #1
Opened 2017-07-12 09:50 UTC by sandcha

Connected to [openfisca-web-api/#138](https://github.com/openfisca/openfisca-web-api/issues/138)

Add piwik tracking option.
Its configuration is to be done on the web api side.

2017-07-12 11:38 UTC, fpagnoux requested changes
The Readme is missing:

> Document that behaviour, explain why this is done, explain why there are no CNIL & EU privacy requirements in the README of that package.

2017-07-12 11:38 UTC, fpagnoux commented on .gitignore
> +.DS_Store
Missing line break at the end of file. Editors usually allow you to add end of file line breaks automatically. Maybe Eclipse does it too ?

2017-07-12 11:38 UTC, fpagnoux commented on Makefile
> +all: test
When do we need this ?

2017-07-12 11:38 UTC, fpagnoux commented on Makefile
> +flake8:
Unnecessarily complex. Check out the [country template](https://github.com/openfisca/country-template/blob/master/Makefile#L5-L7) for a much simpler set up.

2017-07-12 11:38 UTC, fpagnoux commented on openfisca_tracker/tests/json/test_calculate.json
> +{
Is this file used anywhere ?

2017-07-12 11:38 UTC, fpagnoux commented on openfisca_tracker/tests/json/test_simulate.json
> +{
Is this file used anywhere ?

2017-07-12 11:38 UTC, fpagnoux commented on setup.cfg
> +ignore = E128,E251,F405,E501, W503
Inconsistent spacing

2017-07-12 11:38 UTC, fpagnoux commented on openfisca_tracker/tests/test_piwik.py
> +# -*- coding: utf-8 -*-
Put there, the tests will be packaged in the distribution (unless you [explicitely exclude them](https://github.com/openfisca/openfisca-web-api/blob/master/setup.py#L65)), which is not great. 

Maybe we can just put them in a `tests` folder at the root directory ?

2017-07-12 11:38 UTC, fpagnoux commented on openfisca_tracker/tests/test_piwik.py
> +    tracker.track('https://api-test.openfisca.fr/variables')  # thread
To avoid messing with our actual stats, we should track a fake URL, such as `https://test-tracking.openfisca.fr/test_track`

2017-07-12 11:38 UTC, fpagnoux commented on openfisca_tracker/tests/test_piwik.py
> +    tracker.track('https://api.openfisca.fr', callback = callback)
Same here.  `https://test-tracking.openfisca.fr/test_track_callback` ?

2017-07-12 11:38 UTC, fpagnoux commented on openfisca_tracker/tests/test_piwik.py
> +    tracker.track('https://api-test.openfisca.fr/variables')  # thread
This single-word comment is not clear not me. What's its purpose ?

2017-07-12 12:01 UTC, sandcha commented on .gitignore
> +.DS_Store
This was  the emacs effect 😬

2017-07-12 12:02 UTC, sandcha commented on Makefile
> +all: test
It's just for the shortcut.

2017-07-12 12:13 UTC, sandcha commented on Makefile
> +flake8:
Done.
Nevertheless, @fpagnoux do we want the tracker to know about the `--country_package`?

2017-07-12 12:15 UTC, sandcha commented on openfisca_tracker/tests/json/test_calculate.json
> +{
Not anymore. Removed.

2017-07-12 12:15 UTC, sandcha commented on openfisca_tracker/tests/json/test_simulate.json
> +{
Not anymore. Removed.

2017-07-12 12:18 UTC, sandcha commented on openfisca_tracker/tests/test_piwik.py
> +# -*- coding: utf-8 -*-
Moved to root directory.

2017-07-12 12:24 UTC, sandcha commented on openfisca_tracker/tests/test_piwik.py
> +    tracker.track('https://api-test.openfisca.fr/variables')  # thread
Removed. Its purpose was to indicate that an instance with a specific life cycle existed here and that it might be tested.

2017-07-12 22:05 UTC, fpagnoux commented on Makefile
> +flake8:
Sorry, it was not clear.

This `flake8 custom instruction is unnecessarily complex. Just use a regular `flake8`, as done in the country template. Of course we want to run our tests, not run `openfisca-run-test` on a folder that doesn't contain any YAML test.

2017-07-12 22:07 UTC, fpagnoux commented on Makefile
> +all: test
Not sure about adding a line of code _just_ for users to be able to write `make` instead of `make test` mak

2017-07-12 22:31 UTC, fpagnoux approved these changes
Ok for the code.

Waiting for more thorough testing to merge though.

2017-07-12 22:37 UTC, sandcha commented
@fpagnoux Is a changelog necessary for first version ? What about circle ci ?

2017-07-12 22:40 UTC, fpagnoux commented
I don't think we have time.

2017-07-13 00:30 UTC, fpagnoux commented on openfisca_tracker/piwik.py
> +    def track(self, action_url, callback = None):
No : if we set callback to `None`, the request will be blocking !

2017-07-28 10:21 UTC, fpagnoux requested changes
Readme needs improvement

2017-07-28 10:21 UTC, fpagnoux commented on README.md
> +If you want to use the existing tracker, your web api package dependencies declares a version of the tracker and you can install it with:
This should not be here. This documents how to launch the API with trackers. It should be on the API repository.

2017-07-28 10:21 UTC, fpagnoux commented on README.md
> +This module works with the OpenFisca Official Web API and its next version, the Preview Web API.
Same, this should not be here, but on the API repositories.

2017-07-28 10:21 UTC, fpagnoux commented on README.md
> +Besides, by configuration, Piwik can anonymize IPs and will respect the "do not track" option on the browsers of the users of the Web API (see its [user privacy information](https://piwik.org/privacy
This is not true. We currently log all calls in piwik, even if a _Do Not Track_ header has been set. However we log no information about it except the time and route.

2017-07-28 13:58 UTC, fpagnoux approved these changes
Code seems good to me, but I've written too much of it to not be biased 😁.

A review by @MattiSG would be welcome.

2017-07-28 13:58 UTC, fpagnoux commented on README.md
> +## Ethics
@MattiSG can you especially look at this part please ?

2017-07-31 18:17 UTC, fpagnoux commented on README.md
> +## Ethics
We need to move on on this issue, so I'm merging.
Feel free to edit this later if it needs improvement.

2017-07-31 18:17 UTC, merged