Track ip
openfisca/tracker pull request #2
Opened 2017-10-04 14:06 UTC by Anna-Livia

Connected to openfisca/openfisca-france#821

This PR adds the possibility to track the API visitor's IP address.

2017-10-06 15:46 UTC, fpagnoux requested changes
Not tested, but here are comments on the code

2017-10-06 15:46 UTC, fpagnoux commented on tests/test_piwik.py
> +TRACKER_URL = 'http://stats.data.gouv.fr/piwik.php'
Why switching to HTTP ? Sending a secret token through HTTP seems risky...

2017-10-06 15:46 UTC, fpagnoux commented on tests/test_piwik.py
> +TRACKER_AUTH = ""
Does the test pass with this value ?

2017-10-06 15:46 UTC, fpagnoux requested changes
Not tested, but here are comments on the code

2017-10-09 10:27 UTC, Anna-Livia commented on tests/test_piwik.py
> +TRACKER_AUTH = ""
Yep :)

2017-10-09 13:10 UTC, fpagnoux approved these changes

2017-10-09 15:29 UTC, fpagnoux commented on openfisca_tracker/piwik.py
> +        log.debug(action_url)
Are we sure we want to log this, especially without any additional context ?

2017-10-09 16:42 UTC, merged