Change request library for python3 compatibility
openfisca/tracker pull request #5
Opened 2018-07-09 08:55 UTC by Anna-Livia

fixes #4

2018-07-09 19:05 UTC, sandcha commented on setup.py
> +        'requests == 2.19'
`requests` seems to be for synchronous HTTP requests while we are looking fo asynchronous requests.
[grequests](https://pypi.org/project/grequests/) library might help us (other libraries exist).

2018-07-10 06:19 UTC, sandcha requested changes
Update from synchronous HTTP requests to asynchronous requests?

> And stop test?

2018-07-10 06:19 UTC, sandcha commented on tests/test_piwik.py
> +# This test never exits. It needs no be manually exited (ctrl + c).
Even if the tracker shouldn't stop, this feature might be useful for test. 
To do so, we can add this code and call `stop_test(tracker)`:
```
    def stop_test(tracker):
        def stop_timer(tracker):
            return
        tracker.stop_timer = types.MethodType(stop_timer, PiwikTracker)
```

2018-07-10 06:19 UTC, sandcha commented on openfisca_tracker/piwik.py
> +            requests.post(
Using [grequests](https://pypi.org/project/grequests/), the syntax looks like this:
```
            rs = (
                grequests.post(self.url, json={"requests": request, "token_auth": self.token_auth})
                for request in self.requests
                )
            grequests.map(rs)
```

2018-07-18 15:59 UTC, sandcha requested changes
Changes on comments (mainly a comment on the number of tracker instances).

2018-07-18 15:59 UTC, sandcha commented on openfisca_tracker/piwik.py
> +        # Lock in case `send()` and `track()` try to access self.requests simultaneously
👍

2018-07-18 15:59 UTC, sandcha commented on tests/test_piwik.py
> +# It might be caused by the timer thread ser in the piwik.py file.
What do you mean by `ser`?

2018-07-18 15:59 UTC, sandcha commented on openfisca_tracker/piwik.py
> +# Each of openfisca-core instance creates a tracker object (1 per worker).
As I understand it, we have multiple gunicorn sync workers that handle/share only one instance of openfisca web api (= one flask app). This instance has one tracker. 
So, we have only one openfisca-core instance and one tracker instance.

2018-07-18 15:59 UTC, sandcha commented on openfisca_tracker/piwik.py
> +
Delete this line to make flake8 happy? 🙂

2018-07-18 16:02 UTC, Anna-Livia commented on tests/test_piwik.py
> +# It might be caused by the timer thread ser in the piwik.py file.
Typo :)

2018-07-18 16:24 UTC, sandcha approved these changes

2018-07-18 16:27 UTC, Anna-Livia commented on openfisca_tracker/piwik.py
> +# Each of openfisca-core instance creates a tracker object (1 per worker).
I traced the tracker object with their ID and `requests`size.
There are 3 distincts tracker object instance when using the API.
The `requests`  length of each increase at different times.

This is why I beleive there are multiple trackers.

2018-07-18 16:56 UTC, merged